export const GET_ALBUMS = 'GET_ALBUMS';
export const ALBUMS_LOADING = 'ALBUMS_LOADING';
export const GET_PHOTOS = 'GET_PHOTOS';
export const CLEAR_PHOTOS = 'CLEAR_PHOTOS';
export const PHOTOS_LOADING = 'PHOTOS_LOADING';
export const GET_USERS = 'GET_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const CLEAR_POSTS = 'CLEAR_POSTS';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_LOADING = 'ADD_POST_LOADING';
export const ADD_POST_LOADING_FAILED = 'ADD_POST_LOADING_FAILED';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_LOADING = 'UPDATE_POST_LOADING';
export const UPDATE_POST_LOADING_FAILED = 'UPDATE_POST_LOADING_FAILED';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_LOADING = 'DELETE_POST_LOADING';
export const DELETE_POST_LOADING_FAILED = 'DELETE_POST_LOADING_FAILED';


// Initial Redux Setup - step 4